# Generated by Django 2.2.13 on 2021-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210224_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='I Want to Publish'),
        ),
    ]
